#config_version=4
mode:
    start_events: lock_lit
    stop_events: start_2ball, start_3ball
    priority: 140

multiball_locks:
    bl_left_lock:
        balls_to_lock: 1
        lock_devices: bd_left_saucer
    bl_right_lock:
        balls_to_lock: 1
        lock_devices: bd_right_saucer

event_player:
    # on eject start 2ball
    sw_ejects{(current_player.bl_left_lock_locked_balls > 0) != (current_player.bl_right_lock_locked_balls > 0)}: start_2ball
    # when both locks are full start 3ball
    multiball_lock_bl_left_lock_locked_ball{(current_player.bl_left_lock_locked_balls > 0) and (current_player.bl_right_lock_locked_balls > 0)}: start_3ball
    multiball_lock_bl_right_lock_locked_ball{(current_player.bl_left_lock_locked_balls > 0) and (current_player.bl_right_lock_locked_balls > 0)}: start_3ball
