#config_version=4
mode:
    start_events: lock_lit
    stop_events: start_2ball, start_3ball
    priority: 140
    restart_on_next_ball: True

multiball_locks:
    bl_lock:
        balls_to_lock: 2
        lock_devices: bd_left_saucer, bd_right_saucer
        reset_count_for_current_player_events: start_2ball, start_3ball
        locked_ball_counting_strategy: min_virtual_physical

scoring:
    sw_ejects{device.multiball_locks.bl_lock["locked_balls"] == 1}:
        mb_multiplier:
            float: 1.5
            action: set

event_player:
    # on eject start 2ball
    sw_ejects{device.multiball_locks.bl_lock["locked_balls"] == 1}: start_2ball
    # when both locks are full start 3ball
    multiball_lock_bl_lock_locked_ball{device.multiball_locks.bl_lock["locked_balls"] == 2}: start_3ball
