#config_version=5

mode:
    start_events: ball_starting
    stop_events:
        sw_skill_shot_cancel
        sw_skill_shot_success
    priority: 200

scoring:
    skill_shot_lit_hit:
        score: 500

shots:
    skill_shot_h:
        switch: pfs_top_lane_h
        profile: sp_skill_shot
        show_tokens:
            light: pfl_top_lane_h
    skill_shot_o:
        advance_events: mode_skill_shot_started
        switch: pfs_top_lane_o
        profile: sp_skill_shot
        show_tokens:
            light: pfl_top_lane_o
    skill_shot_t:
        switch: pfs_top_lane_t
        profile: sp_skill_shot
        show_tokens:
            light: pfl_top_lane_t

shot_profiles:
    sp_skill_shot:
        states:
            - name: unlit
              show: off
            - name: lit
              show: flash
              loops: -1
              speed: 4
            - name: hit
              show: on
        block: yes

shot_groups:
    skill_shot:
        shots: skill_shot_h, skill_shot_o, skill_shot_t
        rotate_left_events: cs_left_flipper_active
        rotate_right_events: cs_right_flipper_active
        reset_events: mode_skill_shot_starting

event_player:
    skill_shot_unlit_hit: sw_skill_shot_cancel
    skill_shot_lit_hit: sw_skill_shot_success
