#config_version=5

mode:
    start_events: start_2ball
    stop_events: multiball_mb_2ball_ended
    priority: 140

multiballs:
    mb_2ball:
        ball_count: 2
        start_events: mode_2ball_started
        shoot_again: 10s
        ball_locks: bd_left_saucer, bd_right_saucer

scoring:
    balldevice_bd_left_saucer_ball_enter:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block
    balldevice_bd_right_saucer_ball_enter:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block
    jackpot.2:
        score: (1000 + current_player.light_jackpot_required_hits * 1000) * current_player.pf_multiplier
    jackpot.1:
        light_jackpot_required_hits: 1
    mode_2ball_started:
        light_jackpot_required_hits: 0

sequences:
    jackpot_sequence:
        events:
            - jackpot_lit
            - balldevice_bd_right_eject_ejecting_ball, balldevice_bd_left_eject_ejecting_ball
        restart_events: jackpot

counters:
    lb_increase_drop_hits_for_light_jackpot:
        count_events: jackpot
        persist_state: True
        events_when_complete: increase_light_jackpot
    lb_enable_jackpot:
        count_events: drop_target_bank_rod_down
        restart_events: jackpot
        count_complete_value: current_player.light_jackpot_required_hits
        events_when_complete: light_jackpot

achievements:
    light_jackpot:
        show_when_started: flash_jackpot
        show_when_completed: off
        start_events:
            light_jackpot: .1s
            multiball_mb_2ball_started: 1s
        events_when_started: jackpot_lit
        reset_events:
            jackpot: 1s
        complete_events: balldevice_bd_right_eject_ejecting_ball, balldevice_bd_left_eject_ejecting_ball
        events_when_completed: jackpot

show_player:
    mode_2ball_started:
        saucer_bounce: play
    multiball_mb_2ball_started:
        flash:
            speed: 2
            loops: 20
            priority: 1000
            show_tokens:
                light: pfl_same_player
    multiball_mb_2ball_shoot_again:
        bell_ring:
            loops: 5
    balldevice_bd_left_eject_ball_eject_attempt{device.sequences.jackpot_sequence["value"]==1}:
        jackpot_left:
            loops: 0
            speed: 20
            priority: 10000
            block_queue: yes
    balldevice_bd_right_eject_ball_eject_attempt{device.sequences.jackpot_sequence["value"]==1}:
        jackpot_right:
            loops: 0
            speed: 20
            priority: 10000
            block_queue: yes
    left_saucer_eject_show_completed:
        saucer_bounce: play
    right_saucer_eject_show_completed:
        saucer_bounce: play
    balldevice_bd_left_saucer_ball_enter:
        left_saucer_eject:
            action: play
            loops: 0
            priority: 10
            events_when_completed: left_saucer_eject_show_completed
    balldevice_bd_right_saucer_ball_enter:
        right_saucer_eject:
            action: play
            loops: 0
            priority: 10
            events_when_completed: right_saucer_eject_show_completed
    jackpot:
        bell_ring_2ball:
            loops: 0
