#config_version=4
mode:
    start_events: start_2ball
    stop_events: multiball_mb_2ball_ended
    priority: 140

multiballs:
    mb_2ball:
        ball_count: 2
        start_events: mode_2ball_started
        shoot_again: 10s
        ball_locks: bd_left_saucer, bd_right_saucer

scoring:
    left_saucer_hit:
        score: 200 * current_player.pf_multiplier
    right_saucer_hit:
        score: 200 * current_player.pf_multiplier
    pfs_drop_r_active:
        score: 20 * current_player.pf_multiplier
    pfs_drop_o_active:
        score: 20 * current_player.pf_multiplier
    pfs_drop_d_active:
        score: 20 * current_player.pf_multiplier
    drop_target_bank_rod_down:
        score: 300 * current_player.pf_multiplier
    rod_in_order_complete:
        score: 300 * current_player.pf_multiplier
    jackpot.2:
        score: 1000 + current_player.light_jackpot_required_hits * 1000 * current_player.pf_multiplier
    jackpot.1:
        light_jackpot_required_hits: 1
    mode_2ball_started:
        light_jackpot_required_hits:
            score: 0
            action: set

logic_blocks:
    counters:
        lb_increase_drop_hits_for_light_jackpot:
            count_events: jackpot
            persist_state: True
            events_when_complete: increase_light_jackpot
        lb_enable_jackpot:
            count_events: drop_target_bank_rod_down
            restart_events: jackpot
            count_complete_value: current_player.light_jackpot_required_hits + 1
            events_when_complete: light_jackpot

achievements:
    light_jackpot:
        show_tokens:
           lights: pfl_left_jackpot, pfl_right_jackpot
        show_when_started: on
        start_events:
            - light_jackpot
            - multiball_mb_2ball_started
        events_when_started: jackpot_lit
        reset_events: 
            - multiball_mb_2ball_started|1
            - jackpot|1
        complete_events: sw_ejects
        events_when_completed: jackpot

show_player:
    jackpot:
        flash_jackpot:
            loops: 10
            speed: 10
    mode_2ball_started:
        ejects_on: play

shows:
    left_eject_off:
        - time: 0
          lights:
              pfl_left_eject: 00
    right_eject_off:
        - time: 0
          lights:
              pfl_right_eject: 00
    flash_jackpot:
        - time: 0
          lights:
              pfl_left_jackpot: ff
              pfl_right_jackpot: ff
        - time: +1
          lights:
              pfl_left_jackpot: 00
              pfl_right_jackpot: 00