#config_version=5

mode:
    start_events: start_2ball
    stop_events: multiball_mb_2ball_ended
    priority: 140

multiballs:
    mb_2ball:
        ball_count: 2
        start_events: mode_2ball_started
        shoot_again: 10s
        ball_locks: bd_left_saucer, bd_right_saucer

scoring:
    balldevice_bd_left_saucer_ball_enter:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block
    balldevice_bd_right_saucer_ball_enter:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block
    jackpot.2:
        score: (1000 + current_player.light_jackpot_required_hits * 1000) * current_player.pf_multiplier
    jackpot.1:
        light_jackpot_required_hits: 1
    mode_2ball_started:
        light_jackpot_required_hits: 0

counters:
    lb_increase_drop_hits_for_light_jackpot:
        count_events: jackpot
        persist_state: True
        events_when_complete: increase_light_jackpot
    lb_enable_jackpot:
        count_events: drop_target_bank_rod_down
        restart_events: jackpot
        count_complete_value: current_player.light_jackpot_required_hits + 1
        events_when_complete: light_jackpot

achievements:
    light_jackpot:
        show_tokens:
           lights: pfl_left_eb, pfl_right_eb
        show_when_started: flash
        show_when_completed: off
        start_events:
            - light_jackpot
            - multiball_mb_2ball_started
        events_when_started: jackpot_lit
        reset_events: 
            - multiball_mb_2ball_started|1
            - jackpot|1
        complete_events: sw_ejects
        events_when_completed: jackpot

show_player:
    balldevice_bd_left_saucer_ball_enter:
        left_saucer_eject:
            loops: 0
            speed: 6
    balldevice_bd_right_saucer_ball_enter:
        right_saucer_eject:
            loops: 0
            speed: 6