#config_version=5

mode:
    start_events: ball_starting
    priority: 500

ball_saves:
    default:
        active_time: 8s
        hurry_up_time: 3s
        grace_period: 2s
        enable_events: mode_ball_save_started
        timer_start_events: 
            balldevice_bd_shooter_lane_ball_left
            sw_skill_shot
            sw_skill_shot_cancel
        auto_launch: no
        balls_to_save: 1

show_player:
    ball_save_default_enabled:
        flash:
            speed: 4
            show_tokens: 
                light: pfl_same_player
    ball_save_default_hurry_up:
        flash:
            speed: 8
            show_tokens:
                light: pfl_same_player
    ball_save_default_grace_period:
        flash:
            action: stop
            show_tokens:
                light: pfl_same_player
    ball_save_default_saving_ball:
        flash:
            action: stop
            show_tokens:
                light: pfl_same_player
        bell_ring:
            loops: 2
    ball_save_default_disabled:
        flash:
            action: stop
            show_tokens:
                light: pfl_same_player