#config_version=5

mode:
    game_mode: false
    start_events: request_to_start_game
    stop_on_ball_end: false
    priority: 5000

show_player:
    mode_player_actions_started:
        player_1_start:
            loops: 0
    player_add_request:
        player_2_start:
            loops: 0
    ball_starting{player==1}:
        player_1_score_on: play
        corvette_on: play
        player_2_score_off: play
        belair_off: play
    ball_starting{player==2}:
        player_2_score_on: play
        belair_on: play
        player_1_score_off: play        
        corvette_off: play
    game_ending:
        game_over:
            loops: 0