#config_version=5

show_player:
    mode_attract_started:
        general_illumination: play
        attract_display_loop: play
        attract_pops: play
        player_1_score_on: play
        player_2_score_on: play
        girl_on: play
        corvette_on: play
        belair_on: play
        bonus_lanes_sweep:
            speed: 3
            loops: -1
        bonus_climb:
            speed: 3
            loops: -1
        hot_alternate:
            speed: 2
            loops: -1
        left_saucer_sweep:
            speed: 3
            loops: -1
        right_saucer_sweep:
            speed: 3
            loops: -1
        rollovers_multipliers:
            speed: 3
            loops: -1
        ball_in_play_bounce: 
            speed: 1
            loops: -1
        flash_flames: play
