#config_version=5

mode:
    start_events: ball_starting
    code: base.End_of_Ball_Bonus
    priority: 100

scoring:
    # R-O-D Drop Targets
    pfs_drop_r_active:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    pfs_drop_o_active:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    pfs_drop_d_active:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    # Slings
    pfs_left_sling_active:
        score: 10 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    pfs_right_sling_active:
        score: 10 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    # Rollover above Ejects
    pfs_left_upper_active:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    pfs_right_upper_active:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    # Standup switches beside Rollovers above Ejects
    pfs_left_side_active:
        score: 10 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    pfs_right_side_active:
        score: 10 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    # Out and Inlanes
    left_outlane_hit:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    right_outlane_hit:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    left_inlane_hit:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    right_inlane_hit:
        score: 100 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    # Middle Playfield Rollovers
    left_rollover_hit:
        score: 70 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    center_rollover_hit:
        score: 70 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    right_rollover_hit:
        score: 70 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    # Achievement Awards
    bonus_lanes_lit_complete:
        score: 300 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    drop_target_bank_rod_down:
        score: 300 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    hot_in_order_hit:
        score: 2000 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    rod_in_order_hit:
        score: 2000 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    nudge_bonus:
        score: 500
    # Jackpot and Multiplier values
    increase_required:
        required_hits: 1
    timer_2x_multiplier_started:
        pf_multiplier:
            score: 2
            action: set
    timer_2x_multiplier_stopped:
        pf_multiplier:
            score: 1
            action: set
    mode_2ball_started:
        mb_2ball_multipler:
            float: 1.5
            action: set
    mode_2ball_stopped:
        mb_2ball_multipler:
            score: 0
            action: set
    mode_3ball_started:
        mb_3ball_multipler:
            float: 2.5
            action: set
    mode_3ball_stopped:
        mb_3ball_multipler:
            score: 0
            action: set

counters:
    # R-O-D drops must be hit to light lock, and the number of times it must be done increases after each jackpot
    lb_increase_drop_hits_for_light_lock:
        count_events: multiball_mb_2ball_ended
        persist_state: True
        events_when_complete: increase_required
    lb_light_lock:
        count_events: drop_target_bank_rod_down
        enable_events: mode_saucer_started
        disable_events: mode_saucer_stopped
        reset_events: multiball_mb_2ball_ended, multiball_mb_3ball_ended
        count_complete_value: current_player.required_hits + 1
        events_when_complete: lock_start
        persist_state: True
    # 1,000 Bonus awarded for completing H-O-T Lanes, In and Outlanes, and each single outlane
    lb_bonus:
        count_events:
            - hot_lanes_lit_complete
            - bonus_lanes_lit_complete
            - left_outlane_hit
            - right_outlane_hit
        starting_count: 0
        count_interval: 1000
        count_complete_value: 10000
        direction: up
        reset_on_complete: False
        reset_events: mode_base_starting
        events_when_complete: bonus_max
    # Top saucers are used as ball locks when enabled
    lb_lock:
        count_events:
            - balldevice_bd_left_saucer_ball_enter
            - balldevice_bd_right_saucer_ball_enter
        starting_count: 1
        count_complete_value: 3
        direction: up
        persist_state: True
        enable_events: lock_start
        reset_events: multiball_mb_2ball_ended, multiball_mb_3ball_ended
        events_when_complete: lock_lit

sequences:
    # Nudge skill shot doubles award and enables locks
    lb_skill_shot:
        events: sw_skill_shot_success
        reset_events: ball_starting
        events_when_complete: lock_start, nudge_bonus
        disable_events: sw_flipper
    lb_left_ball_locked:
        events: ball_lock_bl_left_lock_locked_ball
        reset_events: mode_lock_started
        events_when_complete: ball_locked
    lb_right_ball_locked:
        events: ball_lock_bl_right_lock_locked_ball
        reset_events: mode_lock_started
        events_when_complete: ball_locked
    # Center Rollovers enable 2X playfield multiplier
    lb_rollovers:
        events: rollovers_lit_complete
        events_when_hit: start_2x

accruals:
    # Extra Ball is lit after completing H-O-T R-O-D and all In and Outlanes
    lb_extra_ball:
        events:
            - hot_lanes_lit_complete
            - bonus_lanes_lit_complete
            - drop_target_bank_rod_down
        events_when_complete: extra_ball_lit

timers:
    2x_multiplier:
        start_value: 20
        end_value: 0
        direction: down
        start_running: no
        control_events:
            - event: start_2x
              action: restart

sequence_shots:
    # Special bonus awarded for getting H-O-T and R-O-D in order
    hot_in_order:
        switch_sequence: pfs_top_lane_h,pfs_top_lane_o,pfs_top_lane_t
    rod_in_order:
        switch_sequence: pfs_drop_r,pfs_drop_o,pfs_drop_d

shots:
    right_outlane:
        switch: pfs_right_outlane
        show_tokens:
            light: pfl_right_outlane
    right_inlane:
        switch: pfs_right_inlane
        show_tokens:
            light: pfl_right_inlane
    left_outlane:
        switch: pfs_left_outlane
        show_tokens:
            light: pfl_left_outlane
    left_inlane:
        switch: pfs_left_inlane
        show_tokens:
            light: pfl_left_inlane
    left_rollover:
        switch: pfs_left_rollover
        show_tokens:
            light: pfl_left_rollover
    center_rollover:
        switch: pfs_center_rollover
        show_tokens:
            light: pfl_center_rollover
    right_rollover:
        switch: pfs_right_rollover
        show_tokens:
            light: pfl_right_rollover

shot_profiles:
    # Flash the Saucer lights to indicate lock status
    sp_lock:
        states:
            - name: lock_1
              show: flash_lock_123
            - name: lock_2
              show: flash_lock_23
            - name: lock_3
              show: flash_lock_3
            - name: lit
              show: flash_lock_4
            - name: unlit
              show: flash_lock_off
    sp_extra_ball:
        states:
            - name: lit
              show: on
            - name: hit
              show: flash_extra_ball

shot_groups:
    bonus_lanes:
        shots: left_outlane,left_inlane,right_inlane,right_outlane
        rotate_left_events: cs_left_flipper_active
        rotate_right_events: cs_right_flipper_active
        reset_events: 
            bonus_lanes_lit_complete: 1s
    rollovers:
        shots: left_rollover,center_rollover,right_rollover
        reset_events:
            rollovers_lit_complete: 1s

show_player:
    ball_started:
        general_illumination: play
        girl_on: play
        title_on: play

    pfs_left_sling_active:
        flash:
           loops: 0
           speed: 2
           priority: 1
           show_tokens:
               light: pfl_left_sling_2

    pfs_right_sling_active:
        flash:
           loops: 0
           speed: 2
           priority: 1
           show_tokens:
               light: pfl_right_sling_2

    mode_2ball_started:
        flash_left_eject: stop
        flash_right_eject: stop
        
    player_shot_left_lock{value==3}:
        flash_left_eject: 
            action: play
            priority: 10
        flash_right_eject: 
            action: play
            priority: 10
    player_shot_right_lock{value==3}:
        flash_left_eject: 
            action: play
            priority: 10
        flash_right_eject: 
            action: play
            priority: 10

    bonus_lanes_lit_complete: 
        bonus_lanes_complete:
            loops: 4
            speed: 4

    rollovers_lit_complete:
        flash_rollover:
            loops: 4
            speed: 4

    timer_2x_multiplier_started:
        flash_2x: 
            action: play
            sync_ms: 500

    timer_2x_multiplier_stopped:
        flash_2x: stop

    pfs_shooter_lane_inactive:
        flash_flames:
            loops: 5
        flames_on: play

    skill_shot_hit:
        flash_flames:
            loops: 10
        flames_on: play
        bell_ring:
            loops: 5

    extra_ball_awarded:
        same_player_shoots_again: play
        flash_flames:
            loops: 10
        flames_on: play
        bell_ring:
            loops: 3

shows:
    # Multiplier lamps
    flash_2x:
        - duration: 250ms
          lights:
              pfl_2x: ff
        - duration: 250ms
          lights: 
              pfl_2x: 00

    flash_4x:
        - duration: 250ms
          lights:
              pfl_4x: ff
        - duration: 250ms
          lights: 
              pfl_4x: 00

    # Left saucer lamps indicating lock status
    flash_left_1:
        - duration: 250ms
          lights:
              pfl_left_saucer_1: ff
        - duration: 250ms
          lights:
              pfl_left_saucer_1: 00
    flash_left_2:
        - duration: 250ms
          lights:
              pfl_left_saucer_2: ff
        - duration: 250ms
          lights:
              pfl_left_saucer_2: 00
    flash_left_3:
        - duration: 250ms
          lights:
              pfl_left_saucer_3: ff
        - duration: 250ms
          lights:
              pfl_left_saucer_3: 00
    flash_left_4:
        - duration: 250ms
          lights:
              pfl_left_saucer_4: ff
        - duration: 250ms
          lights:
              pfl_left_saucer_4: 00
    flash_left_eject:
        - duration: 100ms
          lights:
              pfl_left_eject: ff
        - duration: 100ms
          lights:
              pfl_left_eject: 00

    # Right saucer lamps indicating lock status
    flash_right_1:
        - duration: 250ms
          lights:
              pfl_right_saucer_1: ff
        - duration: 250ms
          lights:
              pfl_right_saucer_1: 00
    flash_right_2:
        - duration: 250ms
          lights:
              pfl_right_saucer_2: ff
        - duration: 250ms
          lights:
              pfl_right_saucer_2: 00
    flash_right_3:
        - duration: 250ms
          lights:
              pfl_right_saucer_3: ff
        - duration: 250ms
          lights:
              pfl_right_saucer_3: 00
    flash_right_4:
        - duration: 250ms
          lights:
              pfl_right_saucer_4: ff
        - duration: 250ms
          lights:
              pfl_right_saucer_4: 00
    flash_right_eject:
        - duration: 100ms
          lights:
              pfl_right_eject: ff
        - duration: 100ms
          lights:
              pfl_right_eject: 00

    left_lock_off:
        - time: 0
          lights:
              pfl_left_saucer_1: 00
              pfl_left_saucer_2: 00
              pfl_left_saucer_3: 00
              pfl_left_saucer_4: 00
    right_lock_off:
        - time: 0
          lights:
              pfl_right_saucer_1: 00
              pfl_right_saucer_2: 00
              pfl_right_saucer_3: 00
              pfl_right_saucer_4: 00

    # No lock hit
    flash_lock_123:
        - time: 0
          shows:
              flash_left_1: play
              flash_right_1: play
              flash_left_2: play
              flash_right_2: play
              flash_left_3: play
              flash_right_3: play
          lights:
              pfl_left_saucer_4: 00
              pfl_right_saucer_4: 00

    # One lock hit
    flash_lock_23:
        - time: 0
          shows:
              flash_left_2: play
              flash_right_2: play
              flash_left_3: play
              flash_right_3: play
          lights:
              pfl_left_saucer_4: 00
              pfl_left_saucer_1: ff
              pfl_right_saucer_4: 00
              pfl_right_saucer_1: ff

    # Two lock hits
    flash_lock_3:
        - time: 0
          shows:
              flash_left_3: play
              flash_right_3: play
          lights:
              pfl_left_saucer_4: 00
              pfl_left_saucer_2: ff
              pfl_left_saucer_1: ff
              pfl_right_saucer_4: 00
              pfl_right_saucer_2: ff
              pfl_right_saucer_1: ff

    # Three lock hits
    flash_lock_4:
        - time: 0
          shows:
              flash_left_4: play
              flash_right_4: play
          lights:
              pfl_left_saucer_3: ff
              pfl_left_saucer_2: ff
              pfl_left_saucer_1: ff
              pfl_right_saucer_3: ff
              pfl_right_saucer_2: ff
              pfl_right_saucer_1: ff
              
    flash_lock_off:
        - time: 0
          lights:
              pfl_left_saucer_4: 00
              pfl_left_saucer_3: 00
              pfl_left_saucer_2: 00
              pfl_left_saucer_1: 00
              pfl_left_eject: ff
              pfl_right_saucer_4: 00
              pfl_right_saucer_3: 00
              pfl_right_saucer_2: 00
              pfl_right_saucer_1: 00
              pfl_right_eject: ff

    # Extra Ball / Ball Saver lamp
    same_player_shoots_again:
        - time: 0
          lights:
              pfl_same_player: ff

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
