#config_version=5

mode:
    start_events: ball_starting
    stop_events: super_pops_2_start
    priority: 300

scoring:
    sw_pop:
        score: 10 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)

counters:
    sw_pop:
        count_events: sw_pop
        starting_count: 50
        count_complete_value: 0
        direction: down
        events_when_complete: super_pops_2_start

show_player:
    mode_super_pops_1_started:
        on:
            show_tokens:
                lights: pops
    pfs_left_pop_active:
        just_off:
            loops: 0
            priority: 1
            show_tokens:
                lights: pfl_left_pop
    pfs_right_pop_active:
        just_off:
            loops: 0
            priority: 1
            show_tokens:
                lights: pfl_right_pop
    pfs_center_pop_active:
        just_off:
            loops: 0
            priority: 1
            show_tokens:
                lights: pfl_center_pop

shows:
    just_off:
        - duration: 200ms
          lights:
              (lights): 00