#config_version=5

mode:
    code: bonus.Count
    start_events: ball_ended{not modes.game.tilted}
    stop_events: bonus_complete
    use_wait_queue: true
    priority: 600

scoring:
    bonus_value: 
        score: 1000
