#config_version=4
mode:
    start_events: extra_ball_lit
    stop_events: extra_ball_hit
    priority: 170

shots:
    extra_ball:
        switch: pfs_top_lane_o
        reset_events: mode_extra_ball_started
        profile: sp_extra_ball
        show_tokens:
            light: pfl_eb

shot_profiles:
    sp_extra_ball:
        states:
            - name: lit
              show: on
            - name: hit
              show: flash_extra_ball

