#config_version=5

mode:
    start_events: extra_ball_lit
    stop_events: extra_ball_hit
    priority: 170

extra_balls:
    eb:
        award_events: extra_ball_hit

shots:
    extra_ball:
        switch: pfs_top_lane_o
        reset_events: mode_extra_ball_started
        profile: sp_extra_ball
        show_tokens:
            light: pfl_extra_ball
