#config_version=5

mode:
    start_events: ball_starting
    priority: 110

variable_player:
    hot_lanes_lit_hit:
        score: 20 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block
    hot_lanes_unlit_hit:
        score: 50 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block
    hot_lanes_lit_complete:
        score: 300 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)|block

shots:
    top_lane_h:
        switch: pfs_top_lane_h
        show_tokens:
            light: pfl_top_lane_h
    top_lane_o:
        switch: pfs_top_lane_o
        show_tokens:
            light: pfl_top_lane_o
    top_lane_t:
        switch: pfs_top_lane_t
        show_tokens:
            light: pfl_top_lane_t

shot_groups:
    hot_lanes:
        shots: top_lane_h, top_lane_o, top_lane_t
        rotate_left_events: cs_left_flipper_active
        rotate_right_events: cs_right_flipper_active
        reset_events: 
            hot_lanes_lit_complete: 1s

show_player:
    hot_lanes_lit_complete: 
        flash: 
            loops: 4
            speed: 4
            show_tokens:
                lights: hot_lanes
