#config_version=5

mode:
    start_events: ball_starting
    priority: 110

shots:
    top_lane_h:
        switch: pfs_top_lane_h
        show_tokens:
            light: pfl_top_lane_h
    top_lane_o:
        switch: pfs_top_lane_o
        show_tokens:
            light: pfl_top_lane_o
    top_lane_t:
        switch: pfs_top_lane_t
        show_tokens:
            light: pfl_top_lane_t

shot_groups:
    hot_lanes:
        shots: top_lane_h, top_lane_o, top_lane_t
        rotate_left_events: cs_left_flipper_active
        rotate_right_events: cs_right_flipper_active
        reset_events: 
            hot_lanes_lit_complete: 1s

show_player:
    hot_lanes_lit_complete: 
        flash_hot_lanes: 
            loops: 4
            speed: 4

scoring:
    hot_lanes_unlit_hit:
        score: 50 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    hot_lanes_lit_hit:
        score: 10 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)
    hot_lanes_lit_complete:
        score: 300 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)

shows:
    flash_hot_lanes:
        - time: 0
          lights:
              pfl_top_lane_h: ff
              pfl_top_lane_o: ff
              pfl_top_lane_t: ff
        - time: +1
          lights:
              pfl_top_lane_h: 00
              pfl_top_lane_o: 00
              pfl_top_lane_t: 00
