#config_version=5

lights:
    # Tilt
    bbl_tilt:
        number: 1-0-27
        subtype: matrix
        label: Tilt

    # Players
    bbl_player_1_up:
        number: 1-0-28
        subtype: matrix
        label: Player 1 Up
    bbl_player_2_up:
        number: 1-0-29
        subtype: matrix
        label: Player 2 Up

    # Ball in Play
    bbl_ball_in_play_1:
        number: 1-0-22
        subtype: matrix
        label: Ball 1
    bbl_ball_in_play_2:
        number: 1-0-21
        subtype: matrix
        label: Ball 1
    bbl_ball_in_play_3:
        number: 1-0-20
        subtype: matrix
        label: Ball 3
    bbl_ball_in_play_4:
        number: 1-0-19
        subtype: matrix
        label: Ball 4
    bbl_ball_in_play_5:
        number: 1-0-18
        subtype: matrix
        label: Ball 5

    # Game Over
    bbl_game_over:
        number: 1-0-24
        subtype: matrix
        label: Game Over

    # Match 
    bbl_match:
        number: 1-0-10
        subtype: matrix
        label: Match
    bbl_match_00:
        number: 1-0-9
        subtype: matrix
        label: Match 00
    bbl_match_10:
        number: 1-0-8
        subtype: matrix
        label: Match 10
    bbl_match_20:
        number: 1-0-7
        subtype: matrix
        label: Match 20
    bbl_match_30:
        number: 1-0-6
        subtype: matrix
        label: Match 30
    bbl_match_40:
        number: 1-0-5
        subtype: matrix
        label: Match 40
    bbl_match_50:
        number: 1-0-4
        subtype: matrix
        label: Match 50
    bbl_match_60:
        number: 1-0-3
        subtype: matrix
        label: Match 60
    bbl_match_70:
        number: 1-0-2
        subtype: matrix
        label: Match 70
    bbl_match_80:
        number: 1-0-1
        subtype: matrix
        label: Match 80
    bbl_match_90:
        number: 1-0-0
        subtype: matrix
        label: Match 90

    # HOT Lamps
    pfl_top_lane_h:
        number: 0-0-7
        subtype: matrix
        label: Top Lane H
        tags: tilt_lamps, hot_lanes
    pfl_top_lane_o:
        number: 0-0-6
        subtype: matrix
        label: Top Lane O
        tags: tilt_lamps, hot_lanes
    pfl_top_lane_t:
        number: 0-0-5
        subtype: matrix
        label: Top Lane T
        tags: tilt_lamps, hot_lanes

    # Left Saucer Lamps
    pfl_left_saucer_1:
        number: 0-1-18
        subtype: matrix
        label: Left Saucer 1
        tags: tilt_lamps
    pfl_left_saucer_2:
        number: 0-1-19
        subtype: matrix
        label: Left Saucer 2
        tags: tilt_lamps
    pfl_left_saucer_3:
        number: 0-1-20
        subtype: matrix
        label: Left Saucer 3
        tags: tilt_lamps
    pfl_left_saucer_4:
        number: 0-0-8
        subtype: matrix
        label: Left Saucer 4
        tags: tilt_lamps

    # Right Saucer Lamps
    pfl_right_saucer_1:
        number: 0-1-21
        subtype: matrix
        label: Right Saucer 1
        tags: tilt_lamps
    pfl_right_saucer_2:
        number: 0-1-22
        subtype: matrix
        label: Right Saucer 2
        tags: tilt_lamps
    pfl_right_saucer_3:
        number: 0-1-23
        subtype: matrix
        label: Right Saucer 3
        tags: tilt_lamps
    pfl_right_saucer_4:
        number: 0-0-10
        subtype: matrix
        label: Right Saucer 4
        tags: tilt_lamps

    pfl_extra_ball:
        number: 0-0-11
        subtype: matrix
        label: Extra Ball
        tags: tilt_lamps

    # Jackpots
    pfl_right_jackpot:
        number: 0-0-14
        subtype: matrix
        label: Right Jackpot
        tags: tilt_lamps
    pfl_left_jackpot:
        number: 0-0-15
        subtype: matrix
        label: Left Jackpot
        tags: tilt_lamps

    # Bonus
    pfl_bonus_1000:
        number: 0-1-14
        subtype: matrix
        label: Bonus 1,000
        tags: bonus_lamps
    pfl_bonus_2000:
        number: 0-1-9
        subtype: matrix
        label: Bonus 2,000
        tags: bonus_lamps
    pfl_bonus_3000:
        number: 0-1-1
        subtype: matrix
        label: Bonus 3,000
        tags: bonus_lamps
    pfl_bonus_4000:
        number: 0-1-10
        subtype: matrix
        label: Bonus 4,000
        tags: bonus_lamps
    pfl_bonus_5000:
        number: 0-1-2
        subtype: matrix
        label: Bonus 5,000
        tags: bonus_lamps
    pfl_bonus_6000:
        number: 0-1-11
        subtype: matrix
        label: Bonus 6,000
        tags: bonus_lamps
    pfl_bonus_7000:
        number: 0-1-3
        subtype: matrix
        label: Bonus 7,000
        tags: bonus_lamps
    pfl_bonus_8000:
        number: 0-1-12
        subtype: matrix
        label: Bonus 8,000
        tags: bonus_lamps
    pfl_bonus_9000:
        number: 0-1-4
        subtype: matrix
        label: Bonus 9,000
        tags: bonus_lamps
    pfl_bonus_10000:
        number: 0-1-8
        subtype: matrix
        label: Bonus 10,000
        tags: bonus_lamps

    # In and Outlanes
    pfl_left_inlane:
        number: 0-1-7
        subtype: matrix
        label: Left Inlane
        tags: tilt_lamps
    pfl_left_outlane:
        number: 0-1-5
        subtype: matrix
        label: Left Outlane
        tags: tilt_lamps
    pfl_right_outlane:
        number: 0-1-25
        subtype: matrix
        label: Right Outlane
        tags: tilt_lamps
    pfl_right_inlane:
        number: 0-1-26
        subtype: matrix
        label: Right Inlane
        tags: tilt_lamps

    # Multipliers 
    pfl_2x:
        number: 0-1-6
        subtype: matrix
        label: 2X
        tags: tilt_lamps
    pfl_4x:
        number: 0-1-24
        subtype: matrix
        label: 4X
        tags: tilt_lamps

    pfl_same_player:
        number: 0-1-13
        subtype: matrix
        label: Same Player Shoots Again
        tags: tilt_lamps

    # Pop Bumpers
    pfl_center_pop:
        number: 0-1-15
        subtype: matrix
        label: Center Pop
        tags: tilt_lamps, pops
    pfl_left_pop:
        number: 0-1-16
        subtype: matrix
        label: Right Pop
        tags: tilt_lamps, pops
    pfl_right_pop:
        number: 0-1-31
        subtype: matrix
        label: Right Pop
        tags: tilt_lamps, pops

    # Center Rollovers
    pfl_right_rollover:
        number: 0-1-17
        subtype: matrix
        label: Right Rollover
        tags: tilt_lamps
    pfl_left_rollover:
        number: 0-1-29
        subtype: matrix
        label: Left Rollover
        tags: tilt_lamps
    pfl_center_rollover:
        number: 0-1-30
        subtype: matrix
        label: Center Rollover
        tags: tilt_lamps

    # Girl GI
    bbl_girl_right_leg:
        number: 1-0-11
        subtype: matrix
        label: Girl Right Leg
        tags: tilt_lamps
    bbl_girl_mid:
        number: 1-0-15
        subtype: matrix
        label: Girl Middle
        tags: tilt_lamps

    # Player 1 Corvette GI
    bbl_corvette_right_hl:
        number: 1-0-16
        subtype: matrix
        label: Corvette Right Headlight
        tags: tilt_lamps
    bbl_corvette_left_hl:
        number: 1-0-23
        subtype: matrix
        label: Corvette Left Headlight
        tags: tilt_lamps
    bbl_corvette_driver:
        number: 1-0-26
        subtype: matrix
        label: Corvette Driver
        tags: tilt_lamps

    # Player 2 Bel-Air GI
    bbl_belair_right_hl:
        number: 1-0-12
        subtype: matrix
        label: Belair Right Headlight
        tags: tilt_lamps
    bbl_belair_left_hl:
        number: 1-0-13
        subtype: matrix
        label: Belair Left Headlight
        tags: tilt_lamps
    bbl_belair_driver:
        number: 1-0-14
        subtype: matrix
        label: Belair Driver
        tags: tilt_lamps

    # Player 1 Score GI
    bbl_player_1_100k:
        number: 1-0-25
        subtype: matrix
        label: Player 1 100,000
        tags: tilt_lamps
    bbl_player_1_10k:
        number: 1-1-16
        subtype: matrix
        label: Player 1 10,000
        tags: tilt_lamps
    bbl_player_1_1000:
        number: 1-1-17
        subtype: matrix
        label: Player 1 1,000
        tags: tilt_lamps
    bbl_player_1_100:
        number: 1-1-18
        subtype: matrix
        label: Player 1 100
        tags: tilt_lamps
    bbl_player_1_10:
        number: 1-1-19
        subtype: matrix
        label: Player 1 10
        tags: tilt_lamps
    bbl_player_1_1:
        number: 1-1-20
        subtype: matrix
        label: Player 1 1
        tags: tilt_lamps

    # Player 2 Score GI
    bbl_player_2_100k:
        number: 1-1-21
        subtype: matrix
        label: Player 2 100,000
        tags: tilt_lamps
    bbl_player_2_10k:
        number: 1-1-25
        subtype: matrix
        label: Player 2 10,000
        tags: tilt_lamps
    bbl_player_2_1000:
        number: 1-1-28
        subtype: matrix
        label: Player 2 1,000
        tags: tilt_lamps
    bbl_player_2_100:
        number: 1-1-27
        subtype: matrix
        label: Player 2 100
        tags: tilt_lamps
    bbl_player_2_10:
        number: 1-1-24
        subtype: matrix
        label: Player 2 10
        tags: tilt_lamps
    bbl_player_2_1:
        number: 1-1-23
        subtype: matrix
        label: Player 2 1
        tags: tilt_lamps

    # HOT ROD Title flames
    bbl_title_flame_left:
        number: 1-0-30
        subtype: matrix
        label: Title Flame Left
    bbl_title_flame_right:
        number: 1-1-31
        subtype: matrix
        label: Title Flame Right

    # HOT ROD Title
    bbl_title_left:
        number: 1-0-31
        subtype: matrix
        label: Title Left
    bbl_title_mid:
        number: 1-1-29
        subtype: matrix
        label: Title Middle
    bbl_title_right:
        number: 1-1-30
        subtype: matrix
        label: Title Right

    # Playfield General Illumination
    pfl_left_saucer_gi:
        number: 0-0-0
        subtype: matrix
        label: Left Saucer
        tags: gi, tilt_lamps
    pfl_right_saucer_gi:
        number: 0-0-9
        subtype: matrix
        label: Right Saucer
        tags: gi, tilt_lamps
    pfl_left_upper:
        number: 0-0-12
        subtype: matrix
        label: Left Upper
        tags: gi, tilt_lamps
    pfl_right_upper:
        number: 0-0-13
        subtype: matrix
        label: Right Upper
        tags: gi, tilt_lamps
    pfl_right_eject:
        number: 0-1-27
        subtype: matrix
        label: Right Eject
        tags: gi, tilt_lamps
    pfl_left_eject:
        number: 0-1-28
        subtype: matrix
        label: Left Eject
        tags: gi, tilt_lamps
    pfl_left_sling_1:
        number: 0-0-16
        subtype: matrix
        label: Left Sling 1
        tags: gi, tilt_lamps
    pfl_left_sling_2:
        number: 0-0-17
        subtype: matrix
        label: Left Sling 2
        tags: gi, tilt_lamps
    pfl_right_sling_1:
        number: 0-0-18
        subtype: matrix
        label: Right Sling 1
        tags: gi, tilt_lamps
    pfl_right_sling_2:
        number: 0-0-19
        subtype: matrix
        label: Right Sling 2
        tags: gi, tilt_lamps

    # HOT Lanes GI
    pfl_lane_4:
        number: 0-0-1
        subtype: matrix
        label: Lane 4
        tags: gi, tilt_lamps
    pfl_lane_3:
        number: 0-0-2
        subtype: matrix
        label: Lane 3
        tags: gi, tilt_lamps
    pfl_lane_2:
        number: 0-0-3
        subtype: matrix
        label: Lane 2
        tags: gi, tilt_lamps
    pfl_lane_1:
        number: 0-0-4
        subtype: matrix
        label: Lane 1
        tags: gi, tilt_lamps

    # Unused Lamps
    unused_0_17:
        number: 1-0-17
        subtype: matrix
    unused_1_22:
        number: 1-1-22
        subtype: matrix
    unused_1_26:
        number: 1-1-26
        subtype: matrix
    unused_3_20:
        number: 0-0-20
        subtype: matrix
    unused_3_21:
        number: 0-0-21
        subtype: matrix
    unused_3_22:
        number: 0-0-22
        subtype: matrix
    unused_3_23:
        number: 0-0-23
        subtype: matrix
    unused_3_24:
        number: 0-0-24
        subtype: matrix
    unused_3_25:
        number: 0-0-25
        subtype: matrix
    unused_3_26:
        number: 0-0-26
        subtype: matrix
    unused_3_27:
        number: 0-0-27
        subtype: matrix
    unused_3_28:
        number: 0-0-28
        subtype: matrix
    unused_3_29:
        number: 0-0-29
        subtype: matrix
    unused_3_30:
        number: 0-0-30
        subtype: matrix
    unused_3_31:
        number: 0-0-31
        subtype: matrix

# Bacxkbox status lights
info_lights:
    ball_1:
        light: bbl_ball_in_play_1
    ball_2:
        light: bbl_ball_in_play_2
    ball_3:
        light: bbl_ball_in_play_3
    ball_4:
        light: bbl_ball_in_play_4
    ball_5:
        light: bbl_ball_in_play_5
    player_1:
        light: bbl_player_1_up
        tags: player1
    player_2:
        light: bbl_player_2_up
        tags: player2
    tilt:
        light: bbl_tilt
    game_over:
        light: bbl_game_over

