#config_version=5

score_reels:
     score_player_1_10:
         coil_inc: bbc_player_1_10
         switch_0: bbs_player_1_10
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_1_100:
         coil_inc: bbc_player_1_100
         switch_0: bbs_player_1_100
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_1_1000:
         coil_inc: bbc_player_1_1000
         switch_0: bbs_player_1_1000
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_1_10000:
         coil_inc: bbc_player_1_10000
         switch_0: bbs_player_1_10000
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_2_10:
         coil_inc: bbc_player_2_10
         switch_0: bbs_player_2_10
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_2_100:
         coil_inc: bbc_player_2_100
         switch_0: bbs_player_2_100
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_2_1000:
         coil_inc: bbc_player_2_1000
         switch_0: bbs_player_2_1000
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms
     score_player_2_10000:
         coil_inc: bbc_player_2_10000
         switch_0: bbs_player_2_10000
         rollover: True
         limit_hi: 9
         limit_lo: 0
         repeat_pulse_time: 200ms
         hw_confirm_time: 100ms

score_reel_groups:
     player1:
         reels: score_player_1_10000,score_player_1_1000,score_player_1_100,score_player_1_10,None
         tags: player1
         max_simultaneous_coils: 3
         chimes: cc_chime_3, cc_chime_1, cc_chime_2, cc_chime_3, none
     player2:
         reels: score_player_2_10000,score_player_2_1000,score_player_2_100,score_player_2_10,None
         tags: player2
         max_simultaneous_coils: 3
         chimes: cc_chime_3, cc_chime_1, cc_chime_2, cc_chime_3, none
