#config_version=5

switches:
    cs_left_flipper:
        number: 0-2-0
        tags: playfield_active,flipper
    cs_right_flipper:
        number: 0-2-1
        tags: playfield_active,flipper

    cs_coin_1:
        number: 1-2-27
    cs_coin_2:
        number: 1-2-28
    cs_start:
        number: 1-2-26
        tags: start
    cs_tilt_bob:
        number: 1-2-29
        tags: playfield_active, tilt_warning
    cs_slam_tilt:
        number: 1-2-30
        tags: slam_tilt

    bbs_player_2_10000:
        number: 1-2-16
    bbs_player_2_1000:
        number: 1-2-17
    bbs_player_2_100:
        number: 1-2-18
    bbs_player_2_10:
        number: 1-2-19

    bbs_player_1_10000:
        number: 1-2-23
    bbs_player_1_1000:
        number: 1-2-22
    bbs_player_1_100:
        number: 1-2-21
    bbs_player_1_10:
        number: 1-2-20

    bbs_credit_down:
        number: 1-2-24
    bbs_credit_up:
        number: 1-2-25

    pfs_left_sling:
        number: 0-2-8
        tags: playfield_active, skill_shot_cancel
    pfs_right_sling:
        number: 0-2-9
        tags: playfield_active, skill_shot_cancel
    pfs_left_upper:
        number: 0-2-16
        tags: playfield_active, skill_shot_cancel
    pfs_left_side:
        number: 0-2-17
        tags: playfield_active, skill_shot_cancel
    pfs_left_eject:
        number: 0-2-18
        tags: skill_shot_cancel, ejects
    pfs_drop_r:
        number: 0-2-19
        tags: playfield_active, skill_shot_cancel
    pfs_drop_o:
        number: 0-2-20
        tags: playfield_active, skill_shot_cancel
    pfs_drop_d:
        number: 0-2-21
        tags: playfield_active, skill_shot_cancel
    pfs_left_rollover:
        number: 0-2-22
        tags: playfield_active, skill_shot_cancel
    pfs_center_rollover:
        number: 0-2-23
        tags: playfield_active, skill_shot_cancel
    pfs_left_inlane:
        number: 0-2-25
        tags: playfield_active, skill_shot_cancel
    pfs_left_outlane:
        number: 0-2-26
        tags: playfield_active, skill_shot_cancel
    pfs_trough_1:
        number: 0-2-27
    pfs_trough_2:
        number: 0-2-28
    pfs_trough_3:
        number: 0-2-29
    pfs_trough_jam:
        number: 0-2-30
    pfs_right_pop:
        number: 0-3-11
        tags: playfield_active, pop, skill_shot_cancel
    pfs_center_pop:
        number: 0-3-10
        tags: playfield_active, pop, skill_shot_cancel
    pfs_left_pop:
        number: 0-3-1
        tags: playfield_active, pop, skill_shot_cancel
    pfs_shooter_lane:
        number: 0-3-16
    pfs_right_outlane:
        number: 0-3-17
        tags: playfield_active, skill_shot_cancel
    pfs_right_inlane:
        number: 0-3-18 
        tags: playfield_active, skill_shot_cancel
    pfs_right_rollover:
        number: 0-3-20
        tags: playfield_active, skill_shot_cancel
    pfs_right_eject:
        number: 0-3-21
        tags: skill_shot_cancel, ejects
    pfs_right_side:
        number: 0-3-22
        tags: playfield_active, skill_shot_cancel
    pfs_right_upper:
        number: 0-3-23
        tags: playfield_active, skill_shot_cancel
    pfs_top_lane_h:
        number: 0-3-26
        tags: playfield_active
    pfs_top_lane_o:
        number: 0-3-27
        tags: playfield_active
    pfs_top_lane_t:
        number: 0-3-28
        tags: playfield_active
    pfs_right_saucer:
        number: 0-3-30
        tags: skill_shot_cancel
    pfs_left_saucer:
        number: 0-3-31
        tags: skill_shot_cancel

