#config_version=5
    
slide_player:
    credits_added:
        type: text
        text: "%machine|credits_string%"
        expire: 2s
    not_enough_credits:
      - type: text
        text: "%machine|credits_string%"
        expire: 2s
        font: small
        v_pos: bottom
      - type: text
        text: INSERT COINS
        decorators:
          type: blink
          repeats: -1
          on_secs: .1
          off_secs: .1
    enabling_free_play:
        type: text
        text: ENABLING FREE PLAY
        expire: 2s
    enabling_credit_play:
      - type: text
        text: ENABLING CREDIT PLAY
        expire: 2s
      - type: text
        text: "%machine|credits_string%"
        expire: 2s
        font: small
        v_pos: bottom
