#config_version=5

mode:
    game_mode: false
    start_events: mode_base_starting
    stop_on_ball_end: false
    priority: 400

show_player:
    mode_gi_started:
        general_illumination: play
        girl_on: play
        title_on: play
