#config_version=4

tilt:
    tilt_switch_tag: tilt
    warnings_to_tilt: 3
    reset_warnings_events: ball_ended
    multiple_hit_window: 300ms
    settle_time: 5s
    tilt_warnings_player_var: tilt_warnings
    