#config_version=5

tilt:
    tilt_switch_tag: tilt
    warnings_to_tilt: 2
    reset_warnings_events: ball_ended
    tilt_warnings_player_var: tilt_warnings

show_player:
    tilt:
        just_off:
            loops: 4
            show_tokens:
                lights: tilt_lamps
