#config_version=5

tilt:
    tilt_switch_tag: tilt
    warnings_to_tilt: 3
    reset_warnings_events: ball_ended
    multiple_hit_window: 300ms
    settle_time: 5s
    tilt_warnings_player_var: tilt_warnings

show_player:
    tilt:
        general_illumination: stop
        flash:
            loops: 8
            speed: 8
            show_tokens:
                lights: bonus_lamp
        bonus_drain:
            loops: 0