#config_version=5

mode:
    start_events: mode_base_started, multiball_mb_2ball_ended, multiball_mb_3ball_ended
    stop_events: mode_lock_started
    priority: 120

variable_player:
    left_saucer_hit:
        score: 300 * current_player.pf_multiplier
        block: true
    right_saucer_hit:
        score: 300 * current_player.pf_multiplier
        block: true
    # Ejects
    balldevice_bd_left_eject_ball_entered:
        score: 500 * current_player.pf_multiplier
        block: true
    balldevice_bd_right_eject_ball_entered:
        score: 500 * current_player.pf_multiplier
        block: true

shots:
    left_saucer:
        hit_events: balldevice_bd_left_saucer_ball_enter
    right_saucer:
        hit_events: balldevice_bd_right_saucer_ball_enter

show_player:
    balldevice_bd_left_saucer_ball_enter:
        left_saucer_eject:
            loops: 0
    balldevice_bd_right_saucer_ball_enter:
        right_saucer_eject:
            loops: 0
