#config_version=4
mode:
    start_events: mode_base_started, multiball_mb_2ball_ended, multiball_mb_3ball_ended
    stop_events: mode_lock_started
    priority: 120

scoring:
    left_saucer_hit:
        score: 300
    right_saucer_hit:
        score: 300
    pfs_drop_r_active:
        score: 100
    pfs_drop_o_active:
        score: 100
    pfs_drop_d_active:
        score: 100
    drop_target_bank_rod_down:
        score: 300

shots:
    left_saucer:
        hit_events: balldevice_bd_left_saucer_ball_enter
    right_saucer:
        hit_events: balldevice_bd_right_saucer_ball_enter

show_player:
    mode_saucer_started:
        ejects_on: play
    mode_saucer_ended:
        ejects_off: play

shows:
    ejects_on:
        - time: 0
          lights:
              pfl_right_eject: ff
              pfl_left_eject: ff
    ejects_off:
        - time: 0
          lights:
              pfl_right_eject: 00
              pfl_left_eject: 00
