#config_version=5

mode:
    code: match.Match
    start_events: game_ending
    stop_events: match_code_ended
    use_wait_queue: true
    priority: 110

show_player:
    mode_match_ending:
        game_over: 
            loops: 0
            block_queue: yes