#config_version=5

mode:
    code: match.Match
    start_events: game_ending
    use_wait_queue: true
    priority: 110

show_player:
    match_code_ended:
        game_over: 
            loops: 0
            block_queue: yes