#config_version=5

mode:
    start_events: super_pops_2_start
    stop_events: super_pops_1_start
    priority: 300

scoring:
    sw_pop:
        score: 50 * (current_player.pf_multiplier + current_player.mb_2ball_multipler + current_player.mb_3ball_multipler)

show_player:
    mode_super_pops_2_started:
        flash_pops: play
    sw_pop_active:
        just_on:
            loops: 0
            priority: 1
            show_tokens:
                lights: pops
